// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkolkaPerinka.Server.Data;

#nullable disable

namespace SkolkaPerinka.Server.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220416125334_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");
#pragma warning restore 612, 618
        }
    }
}
